### ISSUE TITLE
Issue when running specs comparison using latest docker image - v0.0.54

### ISSUE THREAD

**Issue by Tanmay2711** [pb33f/openapi-changes#101]
Hi Team,

We are running following command in Azure Devops pipeline to compare specs changes. And task gets timed out when using latest docker image.

command -
```docker run --rm -v "$PWD`:/specs`:rw" pb33f/openapi-changes summary /specs/.original.json /specs/schema.json```
Task type = Powershell

Output - 
![image](https://github.com/pb33f/openapi-changes/assets/48334190/9547bfc9-7893-4fbd-9731-bcde081c00cf)

**Comment by daveshanley** [comment]
Can you provide reproducible specs?

**Comment by Tanmay2711** [comment]
Due to some reasons, I can't provide full specs, here is the minimal specs that got changed.
PFA old and new json files.

[new.json](https://github.com/pb33f/openapi-changes/files/14543412/new.json)
[old.json](https://github.com/pb33f/openapi-changes/files/14543413/old.json)

**Comment by daveshanley** [comment]
This can't be replicated with `v0.0.62`
