### ISSUE TITLE
[nice to have] Usability  Color selection is hard to catch

### ISSUE THREAD

**Issue by LasneF** [pb33f/openapi-changes#106]
on the left side 

it s quite hard to see what is selected on not 

![image](https://github.com/pb33f/openapi-changes/assets/12461661/f0219e1d-44f3-4e82-9b36-376251398006)

(it s no only a monitor setting) 

this is then hard to find where we are especially doing an API diff review

**Comment by daveshanley** [comment]
![Screenshot 2024-04-25 at 12 59 18 PM](https://github.com/pb33f/openapi-changes/assets/187345/9876396b-8b88-4d3c-a61e-4469596980c3)

in `v0.0.62` the color has been lightened, so it's easier to read and more accessible.
