### ISSUE TITLE
Enhancement : font size on HTML report

### ISSUE THREAD

**Issue by LasneF** [pb33f/openapi-changes#127]
on a normal resolution , without zoom the font used for the pie chart is barely underadable 

![image](https://github.com/pb33f/openapi-changes/assets/12461661/ba77a1b8-bb5a-4c52-a450-d02a41198dd8)

mayb be increase a bit the font size  , or change the color

**Comment by daveshanley** [comment]
![Screenshot 2024-04-25 at 12 58 06 PM](https://github.com/pb33f/openapi-changes/assets/187345/2d65b4db-5898-4ffb-aec7-dc64a8623e8f)

Resolved in `v0.0.62`
