### ISSUE TITLE
libopenapi outdated, update to 0.18.1

### ISSUE THREAD

**Issue by mguentner** [pb33f/openapi-changes#161]
I am seeing issues with a schema that uses JSON pointer in the current dependency configuration of `openapi-changes`:

```
  ERROR   component '#/components/schemas/OneOrMany<String, PreferOne>' does not exist in the specification
Error: unable to process specifications
```

Using `libopenapi` in **v0.16.2** (the current version openapi-changes requires) in test binary, roughly the code described [here](https://pb33f.io/libopenapi/installing/), results in the same error message.

```
component '#/components/schemas/OneOrMany<String, PreferOne>' does not exist in the specification
```

The same binary with libopenapi **v0.18.1** successfully parses the schema.

```
go mod edit -require github.com/pb33f/libopenapi@v0.18.1 && go get && go build
```
then solves the issue in `openapi-changes` as well. :+1: 

Is anything blocking the update at the moment?

**Comment by mguentner** [comment]
FWIW, just did a bisect in `libopenapi` and https://github.com/pb33f/libopenapi/commit/f33aa2fee0c9ee0ec6b800cfe36eef1506e5e424 fixed the issue.

**Comment by daveshanley** [comment]
Hey sorry. I will be offline for a week or two. I am going through some personal challenges and I am not working.

**Comment by mguentner** [comment]
Closed with https://github.com/pb33f/openapi-changes/commit/c448806114a3ce10a5654f669ca05815301322d3

**Comment by mguentner** [comment]
Thank you!
