### ISSUE TITLE
Feature improvement: Include overall changes statistics in `summary` subcommand

### ISSUE THREAD

**Issue by britneytu** [pb33f/openapi-changes#39]
### What could be improved?
Would it be possible to include the change statistics in `summary` subcommand similar to the one in `html-report`?

For example, in the generated html report, I could see an overview in the number of changes.
<img width="569" alt="Screenshot 2023-07-06 at 3 10 39 PM" src="https://github.com/pb33f/openapi-changes/assets/16813965/a5879de1-117c-4861-a20b-19bc311dbccf">

It would be great to see this kind of information in text form in `summary` subcommand

### What's the use case?
Imagine use the tool in the a git pipeline job and as a developer, I want to get a rough idea on the number of changes made, compared to the previous version. 

It would also be great to put this information at the bottom (near bottom) of the generated text for convenient view :) 

Thank you so much for reading through! 💯

**Comment by daveshanley** [comment]
Sounds great!

**Comment by daveshanley** [comment]
This has been implemented in `v0.0.31`

You can now see expanded metrics on the `summary` command.


![Screenshot 2023-07-24 at 5 10 04 PM](https://github.com/pb33f/openapi-changes/assets/187345/139cbb44-4604-4004-9da9-19ab3f1b4156)
