### ISSUE TITLE
Error with private Gitlab URL

### ISSUE THREAD

**Issue by garymcm** [pb33f/openapi-changes#48]
It may be staring at me in the face, but I can't see it (the blurred part is just a `.foo.com` domain I prefer to keep private):

![image](https://github.com/pb33f/openapi-changes/assets/26325750/dcbd2315-cbd1-4ada-b4c0-64f89637e8a4)

**Comment by daveshanley** [comment]
You will need to check out the repo and run `openapi-changes` on the repo locally.
