### ISSUE TITLE
Graph Display is some how cut 

### ISSUE THREAD

**Issue by LasneF** [pb33f/openapi-changes#63]
taking the sampple provided as ... sample meaning 
https://github.com/pb33f/openapi-changes/blob/main/sample-specs/petstorev3.json 

and analyzing the change explore graphe in horizontal mode it gives 
![image](https://github.com/pb33f/openapi-changes/assets/12461661/35436c96-a1f6-4a10-9d44-6d9090c34ab3)

but in vertical mode it gives 
![image](https://github.com/pb33f/openapi-changes/assets/12461661/874778da-e71d-43a3-9d3c-331df378f3aa)

meaning missing Document as root , and las segment of schema and 400 as highlighted on screen shot

**Comment by daveshanley** [comment]
Yes, this is a problem with my 'display port' code that is deciding how big to make the canvas rendering the graph. I need to tune this up, I was expecting it to start chopping bits off with deep flows.

**Comment by daveshanley** [comment]
I have added a change that increases the canvas size significantly. It seems to work well on all the examples I tried that I know got cut. 

Fixed in `v0.0.53`

![Screenshot 2024-01-19 at 8 42 20 PM](https://github.com/pb33f/openapi-changes/assets/187345/7a289749-f281-4ed0-86ee-1ba25eb9af4f)
