### ISSUE TITLE
Overall Change Pie Chart Counter not ok

### ISSUE THREAD

**Issue by LasneF** [pb33f/openapi-changes#64]
API diff counter pie cournter is wrong when 100 of the changes are breaking 

it display as below 
![image](https://github.com/pb33f/openapi-changes/assets/12461661/3f3c56bc-f636-446e-974a-d0f19b22a7a9)

with the counter beeing 
![image](https://github.com/pb33f/openapi-changes/assets/12461661/e94f0c7b-c683-4a22-89c2-a3b840c517a0)

we have a clear repartion of the changes 1 third added , 2 third remove  that is displayed correctly on the chart

however for the overall changes the percentage are wrong , it let us think that 50 % are breaking vs this is 100%

How to reproduce : 
do API diff on https://github.com/oasis-tcs/odata-openapi/blob/main/examples/odata-rw-v3.openapi3.json

**Comment by daveshanley** [comment]
Looks like some of my math needs checking :D

**Comment by daveshanley** [comment]
Fixed in `v0.0.43`
