### ISSUE TITLE
Const changes aren't correctly detected

### ISSUE THREAD

**Issue by srir** [pb33f/openapi-changes#67]
(unsure whether this is an issue better filed here or with https://github.com/pb33f/libopenapi - feel free to redirect!)

We're trying to use `openapi-changes` to detect breaking spec changes to our production API. 

We're not seeing changes to `const` values detected at all (let alone as "breaking"). I've put together a MWE to demonstrate the issue we're seeing (https://gist.github.com/srir/8513874d960a2fd5fbb380f484e4ffc0)

Expected:
- `openapi-changes summary spec_prod.json spec_new.json` detects and reports a difference
- note: the difference is subtle (a change to the `const` value in the `type` property for each of `ResourceNotFoundError` and `FeatureNotAvailableError`)

Actual:
- no differences are detected; `openapi-changes summary spec_prod.json spec_new.json` exits with the following, and exit code `0`:
```
openapi-changes version: 0.0.42 | compiled: 2023-09-09T15:03:00Z


 INFO  printing summary
```

**Comment by daveshanley** [comment]
Ah, yes! This was a recent addition to `libopenapi` from the community. I don't think it's been wired into the `what-changed` module yet, which is why it's being ignored. 

Technically the issue is in `libopenapi` as `openapi-changes` is really just an interface for the `what-changed`. module.

**Comment by srir** [comment]
makes sense - happy to file it there!

(fwiw, we're using single-element enums as a workaround here, and while not as pretty, it does what we want detection-wise!)

**Comment by daveshanley** [comment]
I have updated the thread in https://github.com/pb33f/libopenapi/issues/178

I am unable to replicate the issue after deeper investigation, can you help?
