### ISSUE TITLE
Report summary display not correctly ordered ( multi threading ? ) 

### ISSUE THREAD

**Issue by LasneF** [pb33f/openapi-changes#94]
when i launch summary command line leverage git  option ie    summary .  directory/mySpec.yaml 

i got the display below 

![image](https://github.com/pb33f/openapi-changes/assets/12461661/5d8f6e9e-aa8e-4031-a5b9-83d3046b63a7)

a quite 'strange' green lon line , 
success then a done completed

then not sure why it finishes with 
![image](https://github.com/pb33f/openapi-changes/assets/12461661/2f61575a-5cc6-4ea3-ae78-a268049e18f0)

not sure

**Comment by LasneF** [comment]
also notice that looks the -l, --limit int     Limit history to number of revisions (default is 5) (default 5) looks not applied

**Comment by daveshanley** [comment]
This is a strange bug, I see what you're seeing.

**Comment by daveshanley** [comment]
This has been fixed in `v0.0.54`
