### ISSUE TITLE
Error message Exit Status 128 : not clear 

### ISSUE THREAD

**Issue by LasneF** [pb33f/openapi-changes#95]
given the command line 
PS D:\code\repos\developer-portal> D:\tools\openapi-changes.exe report  . .\documentations\reference-data\component-descriptor.yml
  ERROR   exit status 128
Error: exit status 128

**Comment by daveshanley** [comment]
This has been enhanced in `v0.0.53`. The `128` error is thrown by git when trying to use git in a non-git repo location. It just throws an unexpected 128 error. `openapi-changes` will now tell you this.
